#!/bin/bash

hook_name="$(basename $0)"
logger "hook: ${hook_name}: hook start"

# run common part of the hook
${SNAP}/bin/snap-hooks-common

# clean ssh-agent.socket
[ -e ${SNAP_DATA}/ssh-agent.socket ] && rm ${SNAP_DATA}/ssh-agent.socket

# upgrading OpenGrok often corrupts indexed history,
# as precaution automatically rebuild index is feature is enabled
# and opengrok version has changed
auto_rebuild="$(snapctl get opengrok.auto-rebuild-index)"
previous_version="$(snapctl get last-opengrok-version=)"
if [ "${auto_rebuild}" = "ON" ] && [ "${SNAP_VERSION}" = "${previous_version}" ]; then
    logger "hook: ${hook_name}: Rebuilding index...(${auto_rebuild},[${SNAP_VERSION}]/[${previous_version}])"
    snapctl start ${SNAP_INSTANCE_NAME}.rebuild-index-helper &
else
    logger "hook: ${hook_name}: No need to rebuild the index. (${auto_rebuild},[${SNAP_VERSION}]/[${previous_version}])"
    # disable reindex helper service
    snapctl stop --disable ${SNAP_INSTANCE_NAME}.rebuild-index-helper
fi
snapctl unset last-opengrok-version
